apiVersion: 2018-10-01
location: centralindia
name: mycontainernew
properties:
  containers:
  - name: dotnetappnew
    properties:
      image: demoregistry3000.azurecr.io/dotnetapp
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      volumeMounts:
      - mountPath: /mounts/secrets
        name: volumesecret
  osType: Linux
  imageRegistryCredentials:
    - server: demoregistry3000.azurecr.io
      username: demoregistry3000
      password: ENqut6JI4GAc1JaUtrQA6TswjJ/AvY
  volumes:
  - name: volumesecret
    secret:
      storage-connection: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXN0YWdpbmdzdG9yZTAwNztBY2NvdW50S2V5PUwrdlpxRXVDQ2M2UkoyVEpOTjdtVitGWEVTYndaN0Q4TGU1L2N3VStOVkdVcWROTVRpZ0VHRTlTOWVSSElrYTBZYndlVHJwMG8zQlF4YTdjNGRlNWlnPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aWkb3dzLm5ldA=
tags: null
type: Microsoft.ContainerInstance/containerGroups